const UiImage = {
    "bike-rent": [
      { name: "Blender", image: "/assets/CoverCarousel/br3.png" },
      { name: "Blender", image: "/assets/CoverCarousel/br2.png" },
      { name: "Blender", image: "/assets/CoverCarousel/br1.png" },
      { name: "Blender", image: "/assets/CoverCarousel/br4.png" },
      { name: "Blender", image: "/assets/CoverCarousel/br5.png" },
      { name: "Blender", image: "/assets/CoverCarousel/br6.png" },
      { name: "Blender", image: "/assets/CoverCarousel/br7.png" },
      { name: "Blender", image: "/assets/CoverCarousel/br8.png" },
      { name: "Blender", image: "/assets/CoverCarousel/br9.png" },
      { name: "Blender", image: "/assets/CoverCarousel/br10.png" },
      { name: "Blender", image: "/assets/CoverCarousel/br11.png" },
      { name: "Blender", image: "/assets/CoverCarousel/br12.png" },

    ],
    "kuih-runner": [
      { name: "Blender", image: "/assets/CoverCarousel/kr3.png" },
      { name: "Blender", image: "/assets/CoverCarousel/kr2.png" },
      { name: "Blender", image: "/assets/CoverCarousel/kr1.png" },
      { name: "Blender", image: "/assets/CoverCarousel/kr4.png" },
      { name: "Blender", image: "/assets/CoverCarousel/kr5.png" },
      { name: "Blender", image: "/assets/CoverCarousel/kr6.png" },
      { name: "Blender", image: "/assets/CoverCarousel/kr7.png" },
    ],
    "kembara-sally": [
      { name: "Blender", image: "/assets/CoverCarousel/ks3.png" },
      { name: "Blender", image: "/assets/CoverCarousel/ks2.png" },
      { name: "Blender", image: "/assets/CoverCarousel/ks7.png" },
      { name: "Blender", image: "/assets/CoverCarousel/ks5.png" },
      { name: "Blender", image: "/assets/CoverCarousel/ks6.png" },
      { name: "Blender", image: "/assets/CoverCarousel/ks4.png" },
      { name: "Blender", image: "/assets/CoverCarousel/ks8.png" },
      { name: "Blender", image: "/assets/CoverCarousel/ks9.png" },
      { name: "Blender", image: "/assets/CoverCarousel/ks10.png" },
      { name: "Blender", image: "/assets/CoverCarousel/ks11.png" },
      { name: "Blender", image: "/assets/CoverCarousel/ks12.png" },
      { name: "Blender", image: "/assets/CoverCarousel/ks13.png" },
      { name: "Blender", image: "/assets/CoverCarousel/ks14.png" },
    ],
    "preschool-learn-grow": [
      { name: "Blender", image: "/assets/CoverCarousel/plg3.png" },
      { name: "Blender", image: "/assets/CoverCarousel/plg2.png" },
      { name: "Blender", image: "/assets/CoverCarousel/plg1.png" },
      { name: "Blender", image: "/assets/CoverCarousel/plg4.png" },
      { name: "Blender", image: "/assets/CoverCarousel/plg5.png" },
      { name: "Blender", image: "/assets/CoverCarousel/plg6.png" },
      { name: "Blender", image: "/assets/CoverCarousel/plg7.png" },
      { name: "Blender", image: "/assets/CoverCarousel/plg8.png" },
      { name: "Blender", image: "/assets/CoverCarousel/plg9.png" },
      { name: "Blender", image: "/assets/CoverCarousel/plg10.png" },
      { name: "Blender", image: "/assets/CoverCarousel/plg11.png" },
      { name: "Blender", image: "/assets/CoverCarousel/plg12.png" },
      { name: "Blender", image: "/assets/CoverCarousel/plg13.png" },
      { name: "Blender", image: "/assets/CoverCarousel/plg14.png" },
      { name: "Blender", image: "/assets/CoverCarousel/plg15.png" },
      { name: "Blender", image: "/assets/CoverCarousel/plg16.png" },
    ],    
  }
  export default UiImage;
